# Generated by Django 5.0 on 2023-12-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
