# Generated by Django 5.0 on 2023-12-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_product_is_published_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_1', models.CharField(max_length=75, verbose_name='product_1')),
                ('version_number', models.PositiveIntegerField(default=None, verbose_name='version_number')),
                ('version_name', models.CharField(max_length=50, verbose_name='version_name')),
                ('current_version', models.PositiveIntegerField(default=None, verbose_name='current_version')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
