# Generated by Django 5.0 on 2024-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0006_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activate'), (False, 'Deactivate')], default=False, verbose_name='is_active'),
        ),
    ]
